wandb_version: 1

model_name:
  desc: null
  value: deepspeechCC
batch_size:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.001
n_epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715204281.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.16.5
      6: 4.40.1
      8:
      - 4
      - 5
      13: darwin-arm64
